"""Initial migration.

Revision ID: 90630ba83784
Revises: 
Create Date: 2025-01-04 17:04:35.374814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90630ba83784'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clients_pkey'),
    sa.UniqueConstraint('email', name='clients_email_key'),
    sa.UniqueConstraint('phone', name='clients_phone_key')
    )
    # ### end Alembic commands ###
